SETTINGS:
  TAB-LIST: true
  SERVER-NAME: 'UHCRUN-01'
  STATS-ITEM:
    ITEM:
      MATERIAL: DIAMOND_SWORD
      DATA: 0
    SLOT: 0
    NAME: '&b&lStatistics'
  SPECTATOR-ITEM:
    ITEM:
      MATERIAL: SKULL_ITEM
      DATA: 0
      SLOT: 0
      NAME: '&b&lSpectate Menu'
  WORLD:
    NAME: 'uhcrun_world'
    SIZE: 750
  GLASS-BORDER:
    ENABLED: true
    DATA: 3
    # Glass Colors Data -> https://pastebin.com/NZw2QC3P
  BORDER:
    SHRINK-UNTIL: 25
    START-BORDER-TIME: 300
    SHRINK-EVERY-SECONDS: 300
    SHRINK-STREAM: 750;500;200;100;50;25
  REQUIRED-PLAYERS: 12
  MAX-PLAYERS: 32
  STARTING-TIME: 30
  SCATTER-TIME: 30
  RESTART-TIME: 10
  PVP-TIME: 600
  HEAL-TIME: 600
  GOD-TIME: 60
  MAX-HEIGHT-TO-PUT-BLOCKS: 90
  ANNOUNCE-COOLDOWN: 20 #Seconds

STATISTICS:
  TITLE: '&bStatistics'
  ITEM-NAME-COLOR: AQUA
  FORMAT: '&f#<number>&7: &b<player> &7» &f<amount>'
  PLAYER-STATS:
    NAME: '&b&lYour Statistics'
    LORE:
      - '&7&m---------------------'
      - '&b&lWins &7» &f<wins>'
      - '&b&lDeaths &7» &f<deaths>'
      - '&b&lKills &7» &f<kills>'
      - '&b&lGames Played &7» &f<games-played>'
      - ''
      - '&b&lGolden Apples &7» &f<golden-apples>'
      - '&b&lDiamond Mined &7» &f<diamond-mined>'
      - '&b&lGold Mined &7» &f<gold-mined>'
      - '&b&lIron Mined &7» &f<iron-mined>'
      - ''
      - '&b&lKDR &7» &f<kdr>'
      - '&7&m---------------------'

SOUNDS:
  START: 'ENDERDRAGON_GROWL'
  START_COUNTDOWN: 'NOTE_PLING'
  BORDER_COUNTDOWN: 'NOTE_PLING'
  BORDER: 'FIREWORK_BLAST'
  PVP_COUNTDOWN: 'NOTE_PLING'
  PVP: 'FIREWORK_BLAST'
  HEAL_COUNTDOWN: 'NOTE_PLING'
  HEAL: 'FIREWORK_BLAST'
  GOD_COUNTDOWN: 'NOTE_PLING'
  GOD: 'ENDERDRAGON_GROWL'