SETTINGS:
  GLASS-BORDER:
    ENABLED: true
    DATA: 14
    # Glass Colors Data -> https://pastebin.com/NZw2QC3P
  REQUIRED-PLAYERS: 3
  MAX-PLAYERS: 32
  STARTING-TIME: 30
  RESTART-TIME: 10

SOUNDS:
  START: 'NOTE_PLING'